name: Deployment to Azure Static Web Apps

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  NODE_VERSION: "14.x"
  NEXT_PUBLIC_API_URL: "https://api-gpmt.westeurope.cloudapp.azure.com"

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Cache node modules
        id: cache-node
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: npm install
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: npm ci
      
      - name: Run jest unittest
        run: npm run test:unit
      
  deployment:
    runs-on: ubuntu-latest
    name: Deployment to Azure

    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
          
      - name: Cache node modules
        id: cache-node
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: npm install
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: npm ci
      - name: Azure Static Web Apps Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "upload"
          app_location: /
          output_location: /out
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_TOKEN }}
