name: Testing

on:
    push:
        branches: [ master ]

env:
    AZURE_WEBAPP_NAME: gpmt
    AZURE_WEBAPP_PACKAGE_PATH: './out'
    NODE_VERSION: '15.x'
    NEXT_PUBLIC_API_URL: 'http://testing.gpmt.org'

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2

        - name: Use Node.js ${{ env.NODE_VERSION }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ env.NODE_VERSION }}
        
        - name: npm install
          run: npm install
        
        - name: Run eslint
          run: npm run lint


    unittest:
        name: Unittest
        needs: lint
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2

        - name: Use Node.js ${{ env.NODE_VERSION }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ env.NODE_VERSION }}


        - name: npm install
          if: steps.cache-node.outputs.cache-hit != 'true'
          run: npm install
        
        - name: Run jest unittest
          run: npm run test:unit
        
